# Generated by Django 4.0.6 on 2022-07-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceTitle', models.CharField(max_length=100)),
                ('serviceSubTitle', models.CharField(max_length=100)),
                ('serviceBody', models.CharField(max_length=500)),
            ],
        ),
    ]
