# Generated by Django 4.0.6 on 2022-07-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
