# Generated by Django 4.0.6 on 2022-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='serviceBody',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceBodyAR',
            field=models.TextField(max_length=500),
        ),
    ]
