# Generated by Django 4.0.6 on 2022-07-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0007_alter_option_optionbody_alter_option_optionbodyar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serviceSubTitle',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceSubTitleAR',
        ),
    ]
