# Generated by Django 4.0.6 on 2022-07-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discountTitleAR',
            field=models.TextField(default='aaa', max_length=100),
            preserve_default=False,
        ),
    ]
